add code coverage job (#477)
install gcovr

exclude src file and adjust folder

revert other jobs

fix format issue

add cov info to lib

update lib

add lib

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -57,7 +57,6 @@ jobs:
           cmake --build clio-packages/build --parallel $(nproc)
           cp ./clio-packages/build/clio-prefix/src/clio-build/clio_tests .
           mv ./clio-packages/build/*.${{ matrix.type.suffix }} .
-
       - name: Artifact packages
         uses: actions/upload-artifact@v3
         with:
@@ -78,8 +77,6 @@ jobs:
       fail-fast: false
       matrix:
         os:
-          - name: ubuntu-22.04
-            experimental: true
           - name: macos-11
             experimental: true
           - name: macos-12
@@ -110,7 +107,6 @@ jobs:
           mac_flags='cxxflags="-std=c++14"'
         fi
         ./b2 ${mac_flags}
-
     - name: install deps
       run: |
         if [[ ${{ matrix.os.name }} =~ mac ]];then
@@ -118,7 +114,6 @@ jobs:
         elif [[ ${{matrix.os.name }} =~ ubuntu ]];then
             sudo apt-get -y install git pkg-config protobuf-compiler libprotobuf-dev libssl-dev wget build-essential doxygen bison flex autoconf clang-format
         fi
-
     - name: Build clio
       run: |
         export BOOST_ROOT=$(pwd)/boost
@@ -127,7 +122,7 @@ jobs:
         if ! cmake --build build -j$(nproc); then
           echo '# 🔥${{ matrix.os.name }}🔥 failed!💥' >> $GITHUB_STEP_SUMMARY
         fi
-
+        
   test_clio:
     name: Test Clio
     runs-on: [self-hosted, Linux]
@@ -147,3 +142,65 @@ jobs:
       - name: Run tests
         timeout-minutes: 10
         uses: ./.github/actions/test
+
+  code_coverage:
+    name: Build on Linux and code coverage
+    needs: lint
+    continue-on-error: false
+    runs-on: ubuntu-22.04
+
+    steps:
+    - uses: actions/checkout@v3
+      with:
+        path: clio
+
+    - name: Check Boost cache
+      id: boost
+      uses: actions/cache@v3
+      with:
+        path: boost
+        key: ${{ runner.os }}-boost
+
+    - name: Build boost
+      if: steps.boost.outputs.cache-hit != 'true'
+      run: |
+        curl -s -OJL "https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.gz"
+        tar zxf boost_1_77_0.tar.gz
+        mv boost_1_77_0 boost
+        cd boost
+        ./bootstrap.sh
+        ./b2
+
+    - name: install deps
+      run: |
+          sudo apt-get -y install git pkg-config protobuf-compiler libprotobuf-dev libssl-dev wget build-essential doxygen bison flex autoconf clang-format gcovr
+
+    - name: Build clio
+      run: |
+        export BOOST_ROOT=$(pwd)/boost
+        cd clio
+        cmake -B build -DCODE_COVERAGE=on -DTEST_PARAMETER='--gtest_filter="-Backend*"'
+        if ! cmake --build build -j$(nproc); then
+          echo '# 🔥Ubuntu build🔥 failed!💥' >> $GITHUB_STEP_SUMMARY
+        fi
+        cd build
+        make clio_tests-ccov
+
+    - name: Code Coverage Summary Report
+      uses: irongut/CodeCoverageSummary@v1.2.0
+      with:
+        filename: clio/build/clio_tests-gcc-cov/out.xml
+        badge: true
+        output: both
+        format: markdown
+
+    - name: Save PR number and ccov report
+      run: |
+          mkdir -p ./UnitTestCoverage
+          echo ${{ github.event.number }} > ./UnitTestCoverage/NR
+          cp clio/build/clio_tests-gcc-cov/report.html ./UnitTestCoverage/report.html
+          cp code-coverage-results.md ./UnitTestCoverage/out.md
+    - uses: actions/upload-artifact@v2
+      with:
+        name: UnitTestCoverage
+        path: UnitTestCoverage/
